### ISSUE TITLE
Latest release is 1.5.4 from over a year ago; there have been lots of changes; Need a new release

### ISSUE THREAD

**Issue by JoshuaRowePhantom** [tlaplus/vscode-tlaplus#262]
Should a new release be published soon? Or is there a link to how to install the latest version?

I discovered this when attempting to use the ALIAS keyword in a .cfg file. I see the feature was checked in 6 months ago to the repository, but it's not showing up in my code completion.

**Comment by lemmy** [comment]
You can install the nighty/latest VSCode extension (with a recent snapshot of TLC) from https://marketplace.visualstudio.com/items?itemName=alygin.vscode-tlaplus-nightly.

**Comment by JoshuaRowePhantom** [comment]
Excellent! Can we put this on the front page?

**Comment by lemmy** [comment]
It is the fourth button on the top row of `Readme.md` (https://github.com/tlaplus/vscode-tlaplus/commit/932a0f6f63bd66ee7c58456245e24af20085eac5).  Can you open a PR that better highlights the nightly release in the `Readme.md`?

**Comment by JoshuaRowePhantom** [comment]
I went to go update the Wiki; I think maybe I need to be a contributor to do so?

Anyway, the directions I saw and followed were at https://github.com/tlaplus/vscode-tlaplus/wiki/How-to-Install.

**Comment by JoshuaRowePhantom** [comment]
https://github.com/tlaplus/vscode-tlaplus/pull/263

**Comment by lemmy** [comment]
> I went to go update the Wiki; I think maybe I need to be a contributor to do so?

You should have received an invite to join the project.

**Comment by lemmy** [comment]
Related: https://github.com/tlaplus/vscode-tlaplus/issues/318

**Comment by lemmy** [comment]
Done (see new marketplace organization)
