### ISSUE TITLE
Try the nightly version for the first time, but get nosuchmethoderror?

### ISSUE THREAD

**Issue by 11800222** [tlaplus/vscode-tlaplus#265]
Was ok with the default version,want the debug feature of nightly version.
Just run model check get this err message:

Errors
TLC threw an unexpected exception.

This was probably caused by an error in the spec or model.

See the User Output or TLC Console for clues to what happened.

The exception was a java.lang.NoSuchMethodError

: java.util.ArrayList.toArray(Ljava/util/function/IntFunction;)[Ljava/lang/Object

**Comment by lemmy** [comment]
You need Java 11 or newer.
