### ISSUE TITLE
Does this plugin support translating PlusCal to TLA+?

### ISSUE THREAD

**Issue by vimalk78** [tlaplus/vscode-tlaplus#272]
I am following Hillel Wayne's `Practical TLA+` book. The book uses Eclipse based official IDE, which supports `Translate
PlusCal Algorithm` options.
Does this plugin support the same? I am not able to see any such option in Command Pallete

**Comment by lemmy** [comment]
https://github.com/tlaplus/vscode-tlaplus/wiki/Automatic-Module-Parsing

**Comment by vimalk78** [comment]
thanks @lemmy
