### ISSUE TITLE
Getting `unrecognized option: -noTE` when running TLC

### ISSUE THREAD

**Issue by ele7ija** [tlaplus/vscode-tlaplus#273]
Running vscode-tlaplus `v1.5.4`.

When I try to run the `TLA+: Check model with TLC`, output tab shows the following TLC logs:

```
/usr/lib/jvm/java-11-temurin//bin/java -XX:+UseParallelGC -cp /home/bp/.vscode-oss/extensions/alygin.vscode-tlaplus-1.5.4/tools/tla2tools.jar tlc2.TLC BlockingQueue.tla -tool -modelcheck -coverage 1 -config BlockingQueue.cfg -deadlock -noTE

TLC2 Version 2.16 of 31 December 2020 (rev: cdddf55)
Error: unrecognized option: -noTE
Usage: java tlc2.TLC [-option] inputfile
```

I failed to find the setting to remove the -noTE option which I cannot even find listed in output of `java -XX:+UseParallelGC -cp /home/bp/.vscode-oss/extensions/alygin.vscode-tlaplus-1.5.4/tools/tla2tools.jar tlc2.TLC -help` so am blocked.

**Comment by ele7ija** [comment]
Okay, solved it, weirdly it seems that `tlaplus.tlc.modelChecker.options` was edited with value `-deadlock -noTE`. Is this the default value?

**Comment by ele7ija** [comment]
So the final RCA is that I cloned https://github.com/lemmy/BlockingQueue repo without noticing the custom settings in .vscode folder.

**Comment by lemmy** [comment]
@ele7ija My [BlockingQueue repo installs](https://github.com/lemmy/BlockingQueue/blob/main/.devcontainer/devcontainer.json#L6) a [nightly build](https://marketplace.visualstudio.com/items?itemName=alygin.vscode-tlaplus-nightly) of the TLA+ VSCode extension, which bundles a newer version of TLC that supports the `-noTE` parameter.  If you encounter other problems, consider switching to nightly.
