### ISSUE TITLE
Installing the released and the newest nightly build into VSCode causes problems

### ISSUE THREAD

**Issue by lemmy** [tlaplus/vscode-tlaplus#277]
Users may unintentionally install both the released and nightly builds of VSCode simultaneously. There is currently no way in VSCode to declare these builds as incompatible and prevent users from encountering this issue, as evidenced by the lack of incompatibility declaration by the popular Javascript Debugger extension. A better solution may be to switch to using  [pre-releases](https://code.visualstudio.com/api/working-with-extensions/publishing-extension).

**Comment by keepsimple1** [comment]
Maybe this is already answered somewhere else. The "Last released" seems still to be "3/20/2021".  Is it recommended to use the nightly instead? What's the plan to have a new release?

**Comment by lemmy** [comment]
Regrettably, our resources for release engineering are limited at the moment. Therefore, I recommend relying on the nightly builds for the time being.

**Comment by lemmy** [comment]
This has become obsolete with https://github.com/tlaplus/vscode-tlaplus/pull/328
