### ISSUE TITLE
Check model with TLC is a no-op if there is no PlusCal in the file

### ISSUE THREAD

**Issue by david415** [tlaplus/vscode-tlaplus#293]
Dear vscode-tlaplus maintainer,

There seems to be a bug where the TLA+ plugin does not check the model unless the model contains PlusCal. In other words, for pure TLA+ files it does not work.

My apologies if this is a duplicate of another bug. I did some due diligence but may have overlooked something.

Sincerely,
David

**Comment by david415** [comment]
Here's a minimal TLA+ spec that demonstrates this bug, at least on my laptop it does:

```
---------------------------- MODULE trafficlight ----------------------------

EXTENDS Integers, TLC

VARIABLES red, yellow, green

vars == <<red, yellow, green>>

Init == /\ red = 1
        /\ yellow = 0
        /\ green = 0

Switch == /\ red = 1
          /\ red' = 0
          /\ green' = 1
          /\ yellow' = yellow
       \/ /\ green = 1
          /\ green' = 0
          /\ yellow' = 1
          /\ red' = red
       \/ /\ yellow = 1
          /\ yellow' = 0
          /\ red' = 1
          /\ green' = green
          
Next == Switch          

Spec == Init /\ [][Next]_vars /\ SF_vars(Next)

TypeOK == /\ red \in {0,1}
          /\ green \in {0,1}
          /\ yellow \in {0,1} 

OneLightOnly == red + yellow + green = 1


=============================================================================

```

**Comment by lemmy** [comment]
The extension currently does not automatically generate a stub TLC config file for TLA+ specifications. In my opinion, the autogenerated config for PlusCal specifications is generally not useful unless it is manually corrected and completed. Therefore, I am leaning towards removing the automatic generation of a config stub in order to maintain consistency.

**Comment by FedericoPonzi** [comment]
Closing the issue, now the plugin will let the user know of missing config.
