### ISSUE TITLE
Check Again should reuse the current window

### ISSUE THREAD

**Issue by CIPop** [tlaplus/vscode-tlaplus#295]
Currently, if the `TLA+ Model Checking` view is in a tab with any other editor (e.g. the corresponding cfg, other tla files, etc.), a new split is created.

I would prefer the model checking window to stay in the same place.

To repro:
1. Start with 2 splits side-by-side: one on the left for TLA and on the right for CFG
2. Run `TLA+ : Check model with TLC`
3. Notice that the `TLA+ Model Checking` window opens in the same split with the CFG
4. Click the `Check again` button.

Notice that a 3rd split is now created. Moving the model checker output back will have the same behavior.
Running the `TLA+: Check model with TLC` does not exhibit the same behavior.

Version:  `v2023.7.14` : same behavior on Windows and Mac.

**Comment by afonsonf** [comment]
Hi, thanks for reporting the bug, I have merged a PR that should fix this (#296)

**Comment by lemmy** [comment]
@afonsonf It appears that this pull request makes the extension reuse an old model checking view. That's great except in situations where TLC startup takes some time. During this period, the view might display the result of the previous model checker run, potentially causing confusion. Would it be possible to reset or blank the view when launching TLC?

**Comment by afonsonf** [comment]
> @afonsonf It appears that this pull request makes the extension reuse an old model checking view. That's great except in situations where TLC startup takes some time. During this period, the view might display the result of the previous model checker run, potentially causing confusion. Would it be possible to reset or blank the view when launching TLC?

Yes, in the last PR I made it always use the "open last model results", I will reintroduce the usage of the "open empty window" and properly reset it without closing it up and opening a new one
