### ISSUE TITLE
The `tlaplus.tlaps.check-step` key-binding breaks VSCode's "go to line number" binding

### ISSUE THREAD

**Issue by eddyashton** [tlaplus/vscode-tlaplus#308]
[This change](https://github.com/tlaplus/vscode-tlaplus/commit/a5e9f01242eca26c2ac959467a57c55fe5e9d1bb#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R216) adds a `tlaplus.tlaps.check-step` command, with default binding `ctrl+g ctrl+g`. This conflicts with the existing (VSCode default) binding, where Ctrl + G runs the "Go to Line/Column" command.

The default binding should be changed, to avoid conflicting with any default bindings for system commands.

It looks like none of the existing commands from this extension install key bindings by default, so perhaps this binding should just be removed (and interested users can configure their own, locally).

**Comment by lemmy** [comment]
@eddyashton Is this Windows?  Ctrl + G doesn't seem to be a system command on macOS.
