### ISSUE TITLE
Variables not working as Watch expression

### ISSUE THREAD

**Issue by nano-o** [tlaplus/vscode-tlaplus#311]
Hello, I'm using the latest nightly and watching expressions does not seem to work. Scenario: I set a breakpoint in my specification, the debugger stops there, I set an expression to watch (e.g. "vote", which is a variable in my specification). Now all I see is "vote:" in the watch panel with nothing after the colon  (it doesn't even say "not available"). Stepping more doesn't change it. Am I misunderstanding this feature, or is there a bug?

**Comment by lemmy** [comment]
Please try the next nightly with https://github.com/tlaplus/tlaplus/commit/503a1e483a1909e15fe027043a4db719c8ad8021

**Comment by nano-o** [comment]
Thanks! Now it works for variables but seemingly not anything else (this is strictly better than before, where didn't work at all). Let's say I add the watch expression `vote[p1]`, where `p1` is a model value, then I only get `vote[p1]:` with nothing after.

By the way, I think it's nice to be able to watch a variable as it's more readable than have to open up the state and scroll to find the variable of interest.

**Comment by nano-o** [comment]
Thanks! Maybe just displaying `vote[p1]: unsupported expression` would help users.

**Comment by lemmy** [comment]
Do you want to provide a patch? :-)

https://github.com/tlaplus/tlaplus/blob/503a1e483a1909e15fe027043a4db719c8ad8021/tlatools/org.lamport.tlatools/src/tlc2/debug/TLCStackFrame.java#L536-L563
