### ISSUE TITLE
Replace "alygin.vscode-tlaplus" and "alygin.vscode-tlaplus-nightly" on VSCode Marketplace with TLA+ Foundation owned publisher

### ISSUE THREAD

**Issue by lemmy** [tlaplus/vscode-tlaplus#318]
We've decided to deprecate `alygin.vscode-tlaplus` and `alygin.vscode-tlaplus-nightly` in favor of the TLA+ Foundation controlled `tlaplus.vscode-ide`.

~The released version of this extension, found at [alygin.vscode-tlaplus](https://marketplace.visualstudio.com/items?itemName=alygin.vscode-tlaplus), is severely outdated (last update was in 2021). I suggest to replace the released version with the "nightly build" version, available at [alygin.vscode-tlaplus-nightly](https://marketplace.visualstudio.com/items?itemName=alygin.vscode-tlaplus-nightly).  In other words, I propose to discontinue the "released" version of the extension and instead, updating the main "alygin.vscode-tlaplus" extension with the content from "alygin.vscode-tlaplus-nightly". This will ensure that users have access to the most recent version of the extension. It also addresses the issue that users can install both the "released" and "nightly" versions concurrently, and run into issues due to conflicts between the two versions. By merging them into one, this problem would be resolved.~

Thoughts? @kape1395 @afonsonf @alygin @klinvill @all...

**Comment by lemmy** [comment]
> I agree with this. Also, if the releasing process changes, can we avoid releases if no new commits are on the main branch? Currently, each day, I get notifications on the new TLA+ extension version installed. For some time, it sounded to me like a bug.

I'm also annoyed by those information-free notifications.  If we agree to merge "alygin.vscode-tlaplus" and "alygin.vscode-tlaplus-nightly", [release nightly](https://github.com/tlaplus/vscode-tlaplus/blob/master/.github/workflows/release-nightly.yml) no longer needs to be [scheduled]https://github.com/tlaplus/vscode-tlaplus/blob/0b39653426ddb8511c77b0b67aa0bc090bfe2208/.github/workflows/release-nightly.yml#L4C1-L6C1) but can be triggered by repo-local changes and dispatches from tlaplus/tlaplus.

**Comment by lemmy** [comment]
I've created a new VSCode marketplace publisher that's "owned" by the TLA+ Foundation: https://marketplace.visualstudio.com/items?itemName=tlaplus-lang.tlaplus-lang

@kape1395 @FedericoPonzi Please share your Microsoft account to be added as owners of the marketplace publisher.

**Comment by lemmy** [comment]
* [ ] [Deprecate old extensions](https://code.visualstudio.com/api/working-with-extensions/publishing-extension#deprecating-extensions): https://github.com/microsoft/vscode-discussions/discussions/1 
* [ ] Consider renaming `tlaplus-lang` publisher name to `tlaplus` ([once ADO `tlaplus` name is freed](https://portal.microsofticm.com/imp/v5/incidents/details/533412479/summary))

**Comment by kape1395** [comment]
@lemmy, my account Karolis Petrauskas (k.petrauskas@gmail.com) User Id : 336ed76d-ac43-6c31-9b7e-079e407795b1

**Comment by kape1395** [comment]
I noticed that VSCode complains about the extension ID:

![image](https://github.com/user-attachments/assets/7cde39c7-adf6-4430-8d19-36c93cee6ed6)

**Comment by lemmy** [comment]
> @lemmy, my account Karolis Petrauskas ([k.petrauskas@gmail.com](mailto:k.petrauskas@gmail.com)) User Id : 336ed76d-ac43-6c31-9b7e-079e407795b1

You have been added as an owner of the extension at https://marketplace.visualstudio.com/manage/publishers/tlaplus.  You and I are able to add additional users.

**Comment by lemmy** [comment]
@afonsonf What's your vscode marketplace id?

**Comment by afonsonf** [comment]
> @afonsonf What's your vscode marketplace id?

Hi, my id is 35e6c390-a822-6fb6-8871-861e28fbe73f

**Comment by lemmy** [comment]
Old extensions have been deprecated:

<img width="1756" alt="Screenshot 2024-08-27 at 2 40 28 PM" src="https://github.com/user-attachments/assets/08da712c-76f6-41e1-a3b0-19a85c7defe9">

**Comment by filiptronicek** [comment]
Hi @lemmy, would it, as a part of this change, be possible to publish the extension under the new namespace under https://open-vsx.org/ as well? For context, I'm trying to also mark the extension as deprecated on Open VSX, but the replacement, `tlaplus.vscode-ide` is not yet available.

**Comment by lemmy** [comment]
Done: https://open-vsx.org/extension/tlaplus/vscode-ide

**Comment by filiptronicek** [comment]
Thanks for the superfast turnaround!

**Comment by lemmy** [comment]
@filiptronicek Would you happen to know what breaks our OVSX publishing: https://github.com/tlaplus/vscode-tlaplus/actions/runs/11185435522/job/31098301346 ?

**Comment by filiptronicek** [comment]
@lemmy it looks like you're trying to override version 1.7.0. If you bump the `version` in your package.json, publishing should work.

**Comment by lemmy** [comment]
I see, we don't have to do that with the VSCode marketplace because `vsce publish` accepts a version number:

https://github.com/tlaplus/vscode-tlaplus/blob/250ef519c64738399537c227ef50ebdf249a2a72/.github/workflows/release.yml#L62

Is there a reason why `ovsx publish` doesn't accept a version number?

**Comment by filiptronicek** [comment]
@lemmy interesting find, `ovsx` has a positional argument too, but it accepts a `.vsix` pathname instead of a version. Given the fact that `ovsx` is a wrapper around an internal `vsce`, there are some differences in arguments and flags. Feel free to raise an issue in https://github.com/eclipse/openvsx if you have some suggestions.

**Comment by lemmy** [comment]
@filiptronicek I finally cycled back to this publishing to https://open-vsx.org/ but hit a problem:  https://github.com/eclipse/openvsx/issues/1010#issuecomment-2699718107  Any idea?

**Comment by lemmy** [comment]
Hacked/Fixed upload to https://open-vsx.org in https://github.com/tlaplus/vscode-tlaplus/commit/06da33c124260263ddf3ffe8d7b600bbbd886e95

**Comment by lemmy** [comment]
As of November 21st, the *deprecated* extension https://open-vsx.org/extension/alygin/vscode-tlaplus-nightly has an impressive 110,000 downloads. However, we lack more detailed data to know whether TLA+ users continue to download the deprecated extension. If this number increases in the coming months, we must take actions.

**Comment by lemmy** [comment]
https://github.com/EclipseFdn/open-vsx.org/issues/7250
