### ISSUE TITLE
Support ANSI escape sequence in trace explorer web view

### ISSUE THREAD

**Issue by lemmy** [tlaplus/vscode-tlaplus#320]
TLC supports ANSI escape sequences to, e.g., colorize counterexmples: <img width="936" alt="Screenshot 2024-01-07 at 9 18 23 PM" src="https://github.com/tlaplus/vscode-tlaplus/assets/88777/e2efae4a-c586-4c40-871e-862ec0f87713">

The extension's webview should properly render the ANSI escape sequences:

<img width="1657" alt="image" src="https://github.com/tlaplus/vscode-tlaplus/assets/88777/b94e47e3-49c7-48ca-b9d7-206eac7345d1">

https://github.com/rburns/ansi-to-html appears to come with the relevant functionality.

@afonsonf Please advice if https://github.com/rburns/ansi-to-html would be a sensible choice to support ANSI?

**Comment by afonsonf** [comment]
The library you used (https://github.com/sagemathinc/ansi-to-react) seems to be a good option yes

**Comment by lemmy** [comment]
<img width="1382" alt="image" src="https://github.com/tlaplus/vscode-tlaplus/assets/88777/e2e63c28-f2c7-459c-af83-c4a80bf84c9d">
