### ISSUE TITLE
Coverage has blank Action on both Nightly and TLA+ Foundation's TLA+ VScode, Alygin's version is OK.

### ISSUE THREAD

**Issue by chris-ortiz-wdc** [tlaplus/vscode-tlaplus#329]
It shows like this in both Nightly and TLA+ Foundation's:
![TLA+VScodeErrorReport](https://github.com/user-attachments/assets/b5772f92-826a-4692-a5ef-0b4af80bebfc)

This is shows fine in Alygin's.
![TLA+VScodePassReport](https://github.com/user-attachments/assets/bbf7dc6f-4ceb-46f7-866b-e35791e044ca)

Thanks,
Zitro

**Comment by lemmy** [comment]
@chris-ortiz-wdc Please try uninstalling the `alygin` nightly extension.  The `alygin.vscode-tlaplus*` will be [deprecated sometime soon](https://github.com/microsoft/vscode-discussions/discussions/1) as per https://github.com/tlaplus/vscode-tlaplus/issues/318.

**Comment by chris-ortiz-wdc** [comment]
@lemmy Thanks for the advice. Is there a plan to fix the issue above in TLA+ Foundation? The only way to have that Action in Coverage is having to flip between TLA+ Foundation and Alygin which is not ideal.

**Comment by afonsonf** [comment]
At end of this week I can try to take a look at this bug

**Comment by lemmy** [comment]
I *cannot* reproduce this issue locally:


<img width="2032" alt="image" src="https://github.com/user-attachments/assets/fac4576d-f111-455c-bc09-5afa6d3c919e">



@chris-ortiz-wdc Can you share your spec?

**Comment by chris-ortiz-wdc** [comment]
@lemmy You can try this one. This also shows the same thing.

---- MODULE CPlusCal ----
EXTENDS TLC, Naturals

N == 8

(*--algorithm CPlusCal {
variables u = 24; v \in 1..N ;
{ print <<u, v>>;
    while ( u # 0)
        { if (u < v) { u:=v || v:= u } ;
            u := u - v };
    print <<"have gcd", v>> }}
end algorithm; *)

\* BEGIN TRANSLATION (chksum(pcal) = "9d58d1cb" /\ chksum(tla) = "82babf6b")
VARIABLES pc, u, v

vars == << pc, u, v >>

Init == (* Global variables *)
        /\ u = 24
        /\ v \in 1..N
        /\ pc = "Lbl_1"

Lbl_1 == /\ pc = "Lbl_1"
         /\ PrintT(<<u, v>>)
         /\ pc' = "Lbl_2"
         /\ UNCHANGED << u, v >>

Lbl_2 == /\ pc = "Lbl_2"
         /\ IF u # 0
               THEN /\ IF u < v
                          THEN /\ /\ u' = v
                                  /\ v' = u
                          ELSE /\ TRUE
                               /\ UNCHANGED << u, v >>
                    /\ pc' = "Lbl_3"
               ELSE /\ PrintT(<<"have gcd", v>>)
                    /\ pc' = "Done"
                    /\ UNCHANGED << u, v >>

Lbl_3 == /\ pc = "Lbl_3"
         /\ u' = u - v
         /\ pc' = "Lbl_2"
         /\ v' = v

(* Allow infinite stuttering to prevent deadlock on termination. *)
Terminating == pc = "Done" /\ UNCHANGED vars

Next == Lbl_1 \/ Lbl_2 \/ Lbl_3
           \/ Terminating

Spec == Init /\ [][Next]_vars

Termination == <>(pc = "Done")

\* END TRANSLATION 
====

![TLA+VScodeErrorReport_CPlusCal](https://github.com/user-attachments/assets/a82903b8-51f1-459d-9eb9-e145f206dc65)

**Comment by lemmy** [comment]
Again, it works on my machine™, suggesting that this could be *a Windows issue*?!

<img width="2032" alt="image" src="https://github.com/user-attachments/assets/6551b31e-99cc-4cb0-bccd-14b5a8660e39">

**Comment by afonsonf** [comment]
I was able to reproduce it in windows with both the new extension and the nightly

![image](https://github.com/user-attachments/assets/17282f58-ac00-41c9-a427-04394df70856)
