### ISSUE TITLE
"Check Model with TLC" fails silently if there's no cfg file

### ISSUE THREAD

**Issue by hwayne** [tlaplus/vscode-tlaplus#331]
By fails silently, I mean it doesn't show this popup:

![image](https://github.com/user-attachments/assets/4498616d-2482-40aa-a577-a3689005ae17)

"Check and debug model with TLC" makes the popup appear normally.

This is with the most recent version of the plugin, on Windows.

**Comment by FedericoPonzi** [comment]
Solved by #336
