### ISSUE TITLE
Running invariant condition with VSCode TLA+ extension

### ISSUE THREAD

**Issue by miksula** [tlaplus/vscode-tlaplus#335]
Beginner here: In the Lamport TLA+ video course the invariant is added In the TLA+ Toolbox by:
       - Go to the model overview page in the Toolbox.
       - Navigate to the "Invariants" section
       
How is this done with vscode-tlaplus? I tried to pass it as optio like: `-coverage 1 -inv MyInvariant`, but seems there is no such flag as `-inv`. Should it be configured in the tla file instead?

**Comment by FedericoPonzi** [comment]
Hi! Assuming you have MySpec.tla file, you will need to create a config file called MySpec.cfg in the same directory. There is an option to specify the path to the config file, but in this way it will be picked up automatically.
Inside the .cfg file, you need to specify at least:
```
SPECIFICATION  Spec

CONSTANTS
    Nodes = 3

INVARIANT
    TypeOK

PROPERTIES
   Termination

\* Check presence of deadlocks. It's true by default.
CHECK_DEADLOCK 
    FALSE
```
You can also check https://learntla.com/topics/cli.html#config-format for more info.

**Comment by FedericoPonzi** [comment]
Closing this one for now, please reopen if in doubt or feel free to open a new issue. Also, make sure to check out the wiki: https://github.com/tlaplus/vscode-tlaplus/wiki/Getting-Started and share any feedback you might have

**Comment by miksula** [comment]
Thank you, this clarified the issue.
