### ISSUE TITLE
"Stop model checking" button doesn't work on Windows

### ISSUE THREAD

**Issue by hwayne** [tlaplus/vscode-tlaplus#345]
## Description:

![image](https://github.com/user-attachments/assets/51356c06-2eef-47cf-b13a-60868ce03c3a)

I'm running in simulation mode, so TLC should only stop when I click the "stop" link. Clicking it does nothing. This is also true with regular model checking and unbound models.

### Steps to reproduce:

1. Start a spec
2. Click the "stop" button next to Running

### Expectations:

TLC should stop checking. It continues until it finishes (or forever).

### Version Information:

* Plugin Version: v2024.10.192237
* OS: Windows 11

**Comment by hwayne** [comment]
ACKN, I'll see if I can figure out why that's not working for me.

**Comment by hwayne** [comment]
I've since seen clients stop models without problems, I'll reopen this if I ever figure out what's wrong for me (and it's traceable back to the extension.)

**Comment by lemmy** [comment]
For the record, I believe I’ve observed similar behavior on non-Windows operating systems, such as macOS.
